# Setup .env file for docker-compose in docker-compose dir
## Firefly container vars
echo "LOCAL_PKEY=${LOCAL_PKEY}" >> docker-compose/.env
echo "JWT_ISSUER=${JWT_ISSUER}" >> docker-compose/.env
echo "JWT_AUDIENCE=${JWT_AUDIENCE}" >> docker-compose/.env
echo "JWT_INT_PORT=${JWT_INT_PORT}" >> docker-compose/.env
echo "JWT_EXT_PORT=${JWT_EXT_PORT}" >> docker-compose/.env
echo "GRPC_INT_PORT=${GRPC_INT_PORT}" >> docker-compose/.env
echo "GRPC_EXT_PORT=${GRPC_EXT_PORT}" >> docker-compose/.env
echo "REST_INT_PORT=${REST_INT_PORT}" >> docker-compose/.env
echo "REST_EXT_PORT=${REST_EXT_PORT}" >> docker-compose/.env
## MySQL container vars
echo "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}" >> docker-compose/.env
echo "MYSQL_USERNAME=${MYSQL_USERNAME}" >> docker-compose/.env
echo "MYSQL_PASSWORD=${MYSQL_PASSWORD}" >> docker-compose/.env
echo "MYSQL_DBNAME=${MYSQL_DBNAME}" >> docker-compose/.env
## Agent container vars
echo "SAFE_NAME=${SAFE_NAME}" >> docker-compose/.env
echo "ACCOUNT_NAME=${ACCOUNT_NAME}" >> docker-compose/.env
