- agentName: searchAgent1
  secretMap: []

- agentName: "{{WORKLOAD_ID}}"
  secretMap:
    - secretName: USERNAME
      secretId: "data/vault/{{SAFE_NAME}}/{{ACCOUNT_NAME}}/username"
    - secretName: PASSWORD
      secretId: "data/vault/{{SAFE_NAME}}/{{ACCOUNT_NAME}}/password"
